name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - develop
      
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml
          EXTRA_PACKAGES: gcc python3-dev musl-dev linux-headers
          # GITHUB_DOMAIN: github.myenterprise.com
          REQUIREMENTS: requirements/requirements_doc.txt